<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class EmployeesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('employees')->insert([
            [
                'first_name' => 'Admin',
                'last_name' => 'User',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'admin',
                'email' => 'admin@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567890',
                'login' => 'adminuser',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Secretary1',
                'last_name' => 'User1',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'secretary',
                'email' => 'secretary1@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567891',
                'login' => 'secretaryuser1',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Secretary2',
                'last_name' => 'User2',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'secretary',
                'email' => 'secretary2@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567892',
                'login' => 'secretaryuser2',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Manager1',
                'last_name' => 'User3',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'manager',
                'email' => 'manager1@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567893',
                'login' => 'manageruser1',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Manager2',
                'last_name' => 'User4',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'manager',
                'email' => 'manager2@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567894',
                'login' => 'manageruser2',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'FoodTech1',
                'last_name' => 'User5',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'food_technologist',
                'email' => 'foodtech1@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567895',
                'login' => 'foodtechuser1',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'FoodTech2',
                'last_name' => 'User6',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'food_technologist',
                'email' => 'foodtech2@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567896',
                'login' => 'foodtechuser2',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'FoodTech3',
                'last_name' => 'User7',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'food_technologist',
                'email' => 'foodtech3@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567897',
                'login' => 'foodtechuser3',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'FoodTech4',
                'last_name' => 'User8',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'food_technologist',
                'email' => 'foodtech4@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567898',
                'login' => 'foodtechuser4',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'FoodTech5',
                'last_name' => 'User9',
                'employee_image' => 'employee_images/default_image.jpg',
                'position' => 'food_technologist',
                'email' => 'foodtech5@example.com',
                'email_verified_at' => now(),
                'phone_number' => '1234567899',
                'login' => 'foodtechuser5',
                'password' => Hash::make('password'),
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
